#!/bin/sh
rm -f list.yaml
wget https://raw.githubusercontent.com/chriskempson/base16-templates-source/master/list.yaml

cat >>list.yaml <<EOF
base16-neovim-lush: https://github.com/shebang/base16-neovim-lush
EOF
